Сделал простое приложение для подарков.
gift-team/gift_service pull request #7
Opened 2019-05-21 15:49 UTC by Mikelyangello

Прошу посмотреть и дать ОС.

2019-05-22 09:06 UTC, kgorshkoff requested changes

2019-05-22 09:06 UTC, kgorshkoff commented on giftapp/models.py
> +    link = models.TextField(max_length=250, verbose_name='Ссылка', blank=True)
https://docs.djangoproject.com/en/2.2/ref/models/fields/#urlfield

2019-05-22 09:06 UTC, kgorshkoff commented on giftapp/models.py
> +    price = models.IntegerField(verbose_name='Цена', blank=True, null=True)
Возможно, цена может быть float?

2019-05-22 09:06 UTC, kgorshkoff commented on giftapp/serializers.py
> +        fields = ['id', 'owner', 'name', 'description', 'photo', 'link', 'price', 'collection', ]
Можно сделать проще -` fields = '__all__'` 
Хотя могут быть проблемы, когда выдаёшь их во view. Я, признаться, не понял в чем проблема, но некоторые классы наследования не работают с ним.

2019-05-22 09:06 UTC, kgorshkoff commented on giftapp/models.py
> +    owner = models.ForeignKey(GiftUser, on_delete=models.PROTECT)
А надо ли нам оставлять объект после удаления пользователя, который был удалён? И будем ли мы их вообще удалять или просто делать неактивными?

2019-05-29 10:58 UTC, Mikelyangello commented on giftapp/models.py
> +    link = models.TextField(max_length=250, verbose_name='Ссылка', blank=True)
Хмм, ну пока можно оставить так. Особенно ссылки, мне кажется, могут быть длиннее 200 символов :)

2019-05-29 10:59 UTC, Mikelyangello commented on giftapp/models.py
> +    price = models.IntegerField(verbose_name='Цена', blank=True, null=True)
Да, согласен, исправлю

2019-05-29 10:59 UTC, Mikelyangello commented on giftapp/serializers.py
> +        fields = ['id', 'owner', 'name', 'description', 'photo', 'link', 'price', 'collection', ]
Тогда тоже пока оставляем, раз не все так гладко

2019-05-29 11:00 UTC, Mikelyangello commented on giftapp/models.py
> +    owner = models.ForeignKey(GiftUser, on_delete=models.PROTECT)
Пользователей будем делать неактивными, поэтому можно, наверное, на всякий пожарный случай (вдруг проверка какая или еще чего - удалять будем) поставить CASCADE

2019-05-29 11:14 UTC, Mikelyangello commented on giftapp/models.py
> +    link = models.TextField(max_length=250, verbose_name='Ссылка', blank=True)
Сделал URLField

2019-05-29 11:24 UTC, Mikelyangello commented
В связи с изменением структуры сделал новую ветку и добавил туда все изменения

2019-05-29 11:24 UTC, closed without merging